name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Backend install
        working-directory: backend
        run: |
          npm ci || npm install

      - name: Frontend install
        working-directory: frontend
        run: |
          npm ci || npm install

      - name: Frontend build
        working-directory: frontend
        run: |
          npm run build --if-present

